services:
  - type: web
    name: gelato-erp
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn 'run:create_app()'"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: super-secret-key