"""Add vat_number etc again

Revision ID: 29332f3d0ce0
Revises: e657533e6d61
Create Date: 2025-05-25 22:51:54.462320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29332f3d0ce0'
down_revision = 'e657533e6d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('vat_number')

    # ### end Alembic commands ###
