"""Add ama to Employee

Revision ID: 392cc40d8317
Revises: b702b791f1b1
Create Date: 2025-05-18 14:23:05.800520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392cc40d8317'
down_revision = 'b702b791f1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ama', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('ama')

    # ### end Alembic commands ###
