"""Replace phone with telephone in Employee

Revision ID: 4d44aec07307
Revises: 5ba4b0aebbe9
Create Date: 2025-05-19 16:47:58.831033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d44aec07307'
down_revision = '5ba4b0aebbe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telephone', sa.String(length=20), nullable=True))
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('telephone')

    # ### end Alembic commands ###
